// This code was autogenerated with dbus-codegen-rust, see https://github.com/diwic/dbus-rs

#![allow(dead_code)]
use dbus as dbus;
use dbus::arg;
use dbus::tree;

pub trait OrgPulseAudioExtEqualizing1Manager {
    type Err;
    fn remove_profile(&self, name: &str) -> Result<(), Self::Err>;
    fn get_interface_revision(&self) -> Result<u32, Self::Err>;
    fn get_equalized_sinks(&self) -> Result<Vec<dbus::Path<'static>>, Self::Err>;
    fn get_profiles(&self) -> Result<Vec<String>, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgPulseAudioExtEqualizing1Manager for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn remove_profile(&self, name: &str) -> Result<(), Self::Err> {
        let mut m = r#try!(self.method_call_with_args(&"org.PulseAudio.Ext.Equalizing1.Manager".into(), &"RemoveProfile".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(name);
        }));
        r#try!(m.as_result());
        Ok(())
    }

    fn get_interface_revision(&self) -> Result<u32, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.PulseAudio.Ext.Equalizing1.Manager", "InterfaceRevision")
    }

    fn get_equalized_sinks(&self) -> Result<Vec<dbus::Path<'static>>, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.PulseAudio.Ext.Equalizing1.Manager", "EqualizedSinks")
    }

    fn get_profiles(&self) -> Result<Vec<String>, Self::Err> {
        <Self as dbus::stdintf::org_freedesktop_dbus::Properties>::get(&self, "org.PulseAudio.Ext.Equalizing1.Manager", "Profiles")
    }
}

pub fn org_pulse_audio_ext_equalizing1_manager_server<F, T, D>(factory: &tree::Factory<tree::MTFn<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFn<D>, D>
where
    D: tree::DataType,
    D::Method: Default,
    D::Property: Default,
    T: OrgPulseAudioExtEqualizing1Manager<Err=tree::MethodErr>,
    F: 'static + for <'z> Fn(& 'z tree::MethodInfo<'_, tree::MTFn<D>, D>) -> & 'z T,
{
    let i = factory.interface("org.PulseAudio.Ext.Equalizing1.Manager", data);
    let f = ::std::sync::Arc::new(f);
    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<'_, tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let name: &str = r#try!(i.read());
        let d = fclone(minfo);
        r#try!(d.remove_profile(name));
        let rm = minfo.msg.method_return();
        Ok(vec!(rm))
    };
    let m = factory.method("RemoveProfile", Default::default(), h);
    let m = m.in_arg(("name", "s"));
    let i = i.add_m(m);

    let p = factory.property::<u32, _>("InterfaceRevision", Default::default());
    let p = p.access(tree::Access::Read);
    let fclone = f.clone();
    let p = p.on_get(move |a, pinfo| {
        let minfo = pinfo.to_method_info();
        let d = fclone(&minfo);
        a.append(r#try!(d.get_interface_revision()));
        Ok(())
    });
    let i = i.add_p(p);

    let p = factory.property::<Vec<dbus::Path<'_>>, _>("EqualizedSinks", Default::default());
    let p = p.access(tree::Access::Read);
    let fclone = f.clone();
    let p = p.on_get(move |a, pinfo| {
        let minfo = pinfo.to_method_info();
        let d = fclone(&minfo);
        a.append(r#try!(d.get_equalized_sinks()));
        Ok(())
    });
    let i = i.add_p(p);

    let p = factory.property::<Vec<&str>, _>("Profiles", Default::default());
    let p = p.access(tree::Access::Read);
    let fclone = f.clone();
    let p = p.on_get(move |a, pinfo| {
        let minfo = pinfo.to_method_info();
        let d = fclone(&minfo);
        a.append(r#try!(d.get_profiles()));
        Ok(())
    });
    let i = i.add_p(p);
    i
}

#[derive(Debug, Default)]
pub struct OrgPulseAudioExtEqualizing1ManagerSinkAdded {
    pub sink: dbus::Path<'static>,
}

impl dbus::SignalArgs for OrgPulseAudioExtEqualizing1ManagerSinkAdded {
    const NAME: &'static str = "SinkAdded";
    const INTERFACE: &'static str = "org.PulseAudio.Ext.Equalizing1.Manager";
    fn append(&self, i: &mut arg::IterAppend<'_>) {
        (&self.sink as &dyn arg::RefArg).append(i);
    }
    fn get(&mut self, i: &mut arg::Iter<'_>) -> Result<(), arg::TypeMismatchError> {
        self.sink = r#try!(i.read());
        Ok(())
    }
}

#[derive(Debug, Default)]
pub struct OrgPulseAudioExtEqualizing1ManagerSinkRemoved {
    pub sink: dbus::Path<'static>,
}

impl dbus::SignalArgs for OrgPulseAudioExtEqualizing1ManagerSinkRemoved {
    const NAME: &'static str = "SinkRemoved";
    const INTERFACE: &'static str = "org.PulseAudio.Ext.Equalizing1.Manager";
    fn append(&self, i: &mut arg::IterAppend<'_>) {
        (&self.sink as &dyn arg::RefArg).append(i);
    }
    fn get(&mut self, i: &mut arg::Iter<'_>) -> Result<(), arg::TypeMismatchError> {
        self.sink = r#try!(i.read());
        Ok(())
    }
}

#[derive(Debug, Default)]
pub struct OrgPulseAudioExtEqualizing1ManagerProfilesChanged {
}

impl dbus::SignalArgs for OrgPulseAudioExtEqualizing1ManagerProfilesChanged {
    const NAME: &'static str = "ProfilesChanged";
    const INTERFACE: &'static str = "org.PulseAudio.Ext.Equalizing1.Manager";
    fn append(&self, _: &mut arg::IterAppend<'_>) {
    }
    fn get(&mut self, _: &mut arg::Iter<'_>) -> Result<(), arg::TypeMismatchError> {
        Ok(())
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    type Err;
    fn introspect(&self) -> Result<String, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgFreedesktopDBusIntrospectable for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn introspect(&self) -> Result<String, Self::Err> {
        let mut m = r#try!(self.method_call_with_args(&"org.freedesktop.DBus.Introspectable".into(), &"Introspect".into(), |_| {
        }));
        r#try!(m.as_result());
        let mut i = m.iter_init();
        let data: String = r#try!(i.read());
        Ok(data)
    }
}

pub fn org_freedesktop_dbus_introspectable_server<F, T, D>(factory: &tree::Factory<tree::MTFn<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFn<D>, D>
where
    D: tree::DataType,
    D::Method: Default,
    T: OrgFreedesktopDBusIntrospectable<Err=tree::MethodErr>,
    F: 'static + for <'z> Fn(& 'z tree::MethodInfo<'_, tree::MTFn<D>, D>) -> & 'z T,
{
    let i = factory.interface("org.freedesktop.DBus.Introspectable", data);
    let f = ::std::sync::Arc::new(f);
    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<'_, tree::MTFn<D>, D>| {
        let d = fclone(minfo);
        let data = r#try!(d.introspect());
        let rm = minfo.msg.method_return();
        let rm = rm.append1(data);
        Ok(vec!(rm))
    };
    let m = factory.method("Introspect", Default::default(), h);
    let m = m.out_arg(("data", "s"));
    let i = i.add_m(m);
    i
}

pub trait OrgFreedesktopDBusProperties {
    type Err;
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg>>, Self::Err>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), Self::Err>;
    fn get_all(&self, interface_name: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg>>>, Self::Err>;
}

impl<'a, C: ::std::ops::Deref<Target=dbus::Connection>> OrgFreedesktopDBusProperties for dbus::ConnPath<'a, C> {
    type Err = dbus::Error;

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg>>, Self::Err> {
        let mut m = r#try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"Get".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface_name);
            i.append(property_name);
        }));
        r#try!(m.as_result());
        let mut i = m.iter_init();
        let value: arg::Variant<Box<dyn arg::RefArg>> = r#try!(i.read());
        Ok(value)
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), Self::Err> {
        let mut m = r#try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"Set".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface_name);
            i.append(property_name);
            i.append(value);
        }));
        r#try!(m.as_result());
        Ok(())
    }

    fn get_all(&self, interface_name: &str) -> Result<::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg>>>, Self::Err> {
        let mut m = r#try!(self.method_call_with_args(&"org.freedesktop.DBus.Properties".into(), &"GetAll".into(), |msg| {
            let mut i = arg::IterAppend::new(msg);
            i.append(interface_name);
        }));
        r#try!(m.as_result());
        let mut i = m.iter_init();
        let props: ::std::collections::HashMap<String, arg::Variant<Box<dyn arg::RefArg>>> = r#try!(i.read());
        Ok(props)
    }
}

pub fn org_freedesktop_dbus_properties_server<F, T, D>(factory: &tree::Factory<tree::MTFn<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFn<D>, D>
where
    D: tree::DataType,
    D::Method: Default,
    T: OrgFreedesktopDBusProperties<Err=tree::MethodErr>,
    F: 'static + for <'z> Fn(& 'z tree::MethodInfo<'_, tree::MTFn<D>, D>) -> & 'z T,
{
    let i = factory.interface("org.freedesktop.DBus.Properties", data);
    let f = ::std::sync::Arc::new(f);
    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<'_, tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let interface_name: &str = r#try!(i.read());
        let property_name: &str = r#try!(i.read());
        let d = fclone(minfo);
        let value = r#try!(d.get(interface_name, property_name));
        let rm = minfo.msg.method_return();
        let rm = rm.append1(value);
        Ok(vec!(rm))
    };
    let m = factory.method("Get", Default::default(), h);
    let m = m.in_arg(("interface_name", "s"));
    let m = m.in_arg(("property_name", "s"));
    let m = m.out_arg(("value", "v"));
    let i = i.add_m(m);

    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<'_, tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let interface_name: &str = r#try!(i.read());
        let property_name: &str = r#try!(i.read());
        let value: arg::Variant<Box<dyn arg::RefArg>> = r#try!(i.read());
        let d = fclone(minfo);
        r#try!(d.set(interface_name, property_name, value));
        let rm = minfo.msg.method_return();
        Ok(vec!(rm))
    };
    let m = factory.method("Set", Default::default(), h);
    let m = m.in_arg(("interface_name", "s"));
    let m = m.in_arg(("property_name", "s"));
    let m = m.in_arg(("value", "v"));
    let i = i.add_m(m);

    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<'_, tree::MTFn<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let interface_name: &str = r#try!(i.read());
        let d = fclone(minfo);
        let props = r#try!(d.get_all(interface_name));
        let rm = minfo.msg.method_return();
        let rm = rm.append1(props);
        Ok(vec!(rm))
    };
    let m = factory.method("GetAll", Default::default(), h);
    let m = m.in_arg(("interface_name", "s"));
    let m = m.out_arg(("props", "a{sv}"));
    let i = i.add_m(m);
    i
}
